# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CourseHelper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
  # Pods for CourseHelper

  target 'CourseHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CourseHelper-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CourseHelper-tvOS

  target 'CourseHelper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
